const API='/api';
let token=localStorage.getItem('token');
let user=JSON.parse(localStorage.getItem('user')||'null');
const $=s=>document.querySelector(s);
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function authHeaders(json=true){const h={Authorization:`Bearer ${token}`};if(json)h['Content-Type']='application/json';return h}
async function request(path,options={}){const r=await fetch(API+path,options);if(r.status===401){logout();throw new Error('Sessão expirada')}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||'Erro na operação');return data}
function greeting(){const h=new Date().getHours();return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=user?.name||'Administrador';$('#userRole').textContent=user?.role||'Administrador';$('#today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});loadPage('dashboard') }
function logout(){localStorage.clear();location.reload()}
$('#logout').onclick=logout;
$('#menuToggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
$('#togglePassword').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const f=new FormData(e.target);try{const p=new URLSearchParams();p.set('username',f.get('username'));p.set('password',f.get('password'));const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Falha no acesso');token=d.access_token;user=d.user;localStorage.setItem('token',token);localStorage.setItem('user',JSON.stringify(user));showApp()}catch(err){$('#loginError').textContent=err.message}};
document.querySelectorAll('#mainNav button').forEach(b=>b.onclick=()=>{loadPage(b.dataset.page);document.querySelector('.sidebar').classList.remove('open')});
function active(page,title){document.querySelectorAll('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent=title}
const titles={dashboard:'Dashboard',customers:'Clientes',vehicles:'Veículos',orders:'Ordens de Serviço',products:'Produtos / Estoque',purchases:'Compras',sales:'Vendas / Orçamentos',finance:'Financeiro',cash:'Caixa',reports:'Relatórios',agenda:'Agenda',whatsapp:'WhatsApp',settings:'Configurações',users:'Usuários'};
async function loadPage(page){try{if(page==='dashboard')return dashboard();if(page==='customers')return customers();if(page==='vehicles')return vehicles();if(page==='products')return products();if(page==='orders')return orders();return comingSoon(page,titles[page]||page)}catch(err){$('#page').innerHTML=`<div class="panel"><h3>Não foi possível carregar</h3><p>${esc(err.message)}</p></div>`}}
async function dashboard(){active('dashboard','Dashboard');const d=await request('/dashboard',{headers:authHeaders(false)});const name=(user?.name||'Administrador').split(' ')[0];$('#page').innerHTML=`
<div class="hero">
  <div class="hero-copy"><div class="hello">${greeting()}, ${esc(name)}! 👋</div><h2>Seja bem-vindo ao <strong>Amigão ERP!</strong></h2><p>Aqui sua oficina ganha controle, agilidade e organização para crescer todos os dias.</p></div>
  <img src="assets/mascote-amigao.png" class="hero-mascot" alt="Mascote Amigão">
  <div class="mascot-tip"><strong>💡 Dica do Mascote</strong><p>${d.low_stock?`Você possui ${d.low_stock} produto(s) com estoque baixo. Confira antes da próxima OS.`:'Seu estoque está em dia. Continue registrando todas as movimentações!'}</p></div>
</div>
<div class="metric-grid">
  <div class="metric"><div class="icon">👥</div><strong>${d.customers}</strong><span>CLIENTES CADASTRADOS</span></div>
  <div class="metric"><div class="icon">🚘</div><strong>${d.vehicles}</strong><span>VEÍCULOS CADASTRADOS</span></div>
  <div class="metric"><div class="icon">📦</div><strong>${d.products}</strong><span>PRODUTOS NO ESTOQUE</span></div>
  <div class="metric"><div class="icon">🔧</div><strong>${d.open_orders}</strong><span>OS EM ANDAMENTO</span></div>
  <div class="metric"><div class="icon">⚠</div><strong>${d.low_stock}</strong><span>ITENS COM ESTOQUE BAIXO</span></div>
  <div class="metric"><div class="icon">💰</div><strong>${money(d.inventory_value)}</strong><span>VALOR DO ESTOQUE</span></div>
</div>
<div class="dash-grid">
  <div class="panel dark"><h3>Resumo operacional</h3><div class="finance-row"><span>Produtos cadastrados</span><strong class="in">${d.products}</strong></div><div class="finance-row"><span>Ordens em andamento</span><strong>${d.open_orders}</strong></div><div class="finance-row"><span>Estoque baixo</span><strong class="out">${d.low_stock}</strong></div><div class="finance-row"><span>Valor em estoque</span><strong class="profit">${money(d.inventory_value)}</strong></div></div>
  <div class="panel dark"><h3>Movimento da semana</h3><div class="fake-chart" aria-label="Gráfico ilustrativo"><i style="height:38%"></i><i style="height:52%"></i><i style="height:46%"></i><i style="height:70%"></i><i style="height:91%"></i><i style="height:63%"></i><i style="height:76%"></i></div></div>
  <div class="panel"><div class="alert-card"><img src="assets/mascote-amigao.png" alt="Mascote"><strong>Fique ligado!</strong><p>${d.low_stock?`Há ${d.low_stock} item(ns) que precisam de atenção.`:'Nenhum alerta crítico no momento.'}</p><button class="small-btn" onclick="loadPage('products')">VER ESTOQUE</button></div><h3 style="margin-top:18px">Agenda de hoje</h3><div class="agenda-list"><div class="agenda-item"><b>09:00 — Revisão preventiva</b><small>Confirme o veículo e o responsável</small></div><div class="agenda-item"><b>14:00 — Conferência de estoque</b><small>Revise itens abaixo do mínimo</small></div></div></div>
</div>`}
function modal(title,fields,onSave){const m=document.createElement('div');m.className='modal';m.innerHTML=`<form class="modal-box"><h2>${title}</h2><div class="grid">${fields}</div><div class="actions"><button type="button" class="small-btn secondary">Cancelar</button><button class="small-btn">Salvar</button></div></form>`;document.body.appendChild(m);m.querySelector('.secondary').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();const save=e.submitter;save.disabled=true;save.textContent='Salvando...';try{await onSave(Object.fromEntries(new FormData(e.target)));m.remove()}catch(err){alert(err.message);save.disabled=false;save.textContent='Salvar'}}}
function bindTableSearch(){const input=$('#search');if(!input)return;input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(q))}}
async function customers(){active('customers','Clientes');const rows=await request('/customers',{headers:authHeaders(false)});$('#page').innerHTML=`<div class="toolbar"><input placeholder="Pesquisar cliente" id="search"><button id="new">+ Novo cliente</button></div><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Documento</th><th>Telefone</th><th>E-mail</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.document||'')}</td><td>${esc(x.phone||'')}</td><td>${esc(x.email||'')}</td></tr>`).join('')}</tbody></table></div>`;bindTableSearch();$('#new').onclick=()=>modal('Novo cliente','<label>Nome<input name="name" required></label><label>CPF/CNPJ<input name="document"></label><label>Telefone<input name="phone"></label><label>E-mail<input name="email" type="email"></label><label style="grid-column:1/-1">Observações<textarea name="notes"></textarea></label>',async d=>{await request('/customers',{method:'POST',headers:authHeaders(),body:JSON.stringify(d)});customers()})}
async function vehicles(){active('vehicles','Veículos');const [rows,cs]=await Promise.all([request('/vehicles',{headers:authHeaders(false)}),request('/customers',{headers:authHeaders(false)})]);const names=Object.fromEntries(cs.map(c=>[c.id,c.name]));$('#page').innerHTML=`<div class="toolbar"><input placeholder="Pesquisar veículo" id="search"><button id="new">+ Novo veículo</button></div><div class="table-wrap"><table><thead><tr><th>Placa</th><th>Cliente</th><th>Marca / Modelo</th><th>Ano</th><th>KM</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.plate)}</strong></td><td>${esc(names[x.customer_id]||'')}</td><td>${esc((x.brand||'')+' '+(x.model||''))}</td><td>${esc(x.year||'')}</td><td>${Number(x.mileage||0).toLocaleString('pt-BR')}</td></tr>`).join('')}</tbody></table></div>`;bindTableSearch();$('#new').onclick=()=>{if(!cs.length)return alert('Cadastre um cliente antes do veículo.');modal('Novo veículo',`<label>Cliente<select name="customer_id" required>${cs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Placa<input name="plate" required></label><label>Marca<input name="brand"></label><label>Modelo<input name="model"></label><label>Ano<input name="year"></label><label>Quilometragem<input name="mileage" type="number" value="0"></label>`,async d=>{d.customer_id=Number(d.customer_id);d.mileage=Number(d.mileage||0);await request('/vehicles',{method:'POST',headers:authHeaders(),body:JSON.stringify(d)});vehicles()})}}
async function products(){active('products','Produtos / Estoque');const rows=await request('/products',{headers:authHeaders(false)});$('#page').innerHTML=`<div class="toolbar"><input id="search" placeholder="Pesquisar código, produto ou marca"><div><input id="file" type="file" accept=".csv" hidden><button id="import">⇧ Importar CSV</button> <button id="new">+ Novo produto</button></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Produto</th><th>Estoque</th><th>Mínimo</th><th>Custo</th><th>Venda</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.code)}</td><td><strong>${esc(x.name)}</strong></td><td>${x.stock}</td><td>${x.minimum_stock}</td><td>${money(x.cost)}</td><td>${money(x.price)}</td></tr>`).join('')}</tbody></table></div>`;bindTableSearch();$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{if(!e.target.files[0])return;const fd=new FormData();fd.append('file',e.target.files[0]);try{const d=await request('/products/import',{method:'POST',headers:authHeaders(false),body:fd});alert(`Importação concluída!\nNovos: ${d.created}\nAtualizados: ${d.updated}\nIgnorados: ${d.ignored}`);products()}catch(err){alert(err.message)}};$('#new').onclick=()=>modal('Novo produto','<label>Código<input name="code" required></label><label>Produto<input name="name" required></label><label>Estoque<input name="stock" type="number" step="0.001" value="0"></label><label>Estoque mínimo<input name="minimum_stock" type="number" step="0.001" value="0"></label><label>Custo<input name="cost" type="number" step="0.01" value="0"></label><label>Preço de venda<input name="price" type="number" step="0.01" value="0"></label><label>Categoria<input name="category"></label><label>Marca<input name="brand"></label>',async d=>{await request('/products',{method:'POST',headers:authHeaders(),body:JSON.stringify(d)});products()})}
async function orders(){active('orders','Ordens de Serviço');const [rows,cs,vs]=await Promise.all([request('/work-orders',{headers:authHeaders(false)}),request('/customers',{headers:authHeaders(false)}),request('/vehicles',{headers:authHeaders(false)})]);const cn=Object.fromEntries(cs.map(c=>[c.id,c.name])),vn=Object.fromEntries(vs.map(v=>[v.id,v.plate]));$('#page').innerHTML=`<div class="toolbar"><input id="search" placeholder="Pesquisar OS, cliente ou veículo"><button id="new">+ Nova OS</button></div><div class="table-wrap"><table><thead><tr><th>OS</th><th>Cliente</th><th>Veículo</th><th>Status</th><th>Total</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>#${x.id}</strong></td><td>${esc(cn[x.customer_id]||'')}</td><td>${esc(vn[x.vehicle_id]||'')}</td><td><span class="status">${esc(x.status)}</span></td><td>${money(x.total)}</td></tr>`).join('')}</tbody></table></div>`;bindTableSearch();$('#new').onclick=()=>{if(!cs.length||!vs.length)return alert('Cadastre um cliente e um veículo antes de abrir a OS.');modal('Nova ordem de serviço',`<label>Cliente<select name="customer_id">${cs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Veículo<select name="vehicle_id">${vs.map(v=>`<option value="${v.id}">${esc(v.plate)}</option>`).join('')}</select></label><label>Status<select name="status"><option>Aberta</option><option>Em diagnóstico</option><option>Aguardando aprovação</option><option>Em execução</option><option>Finalizada</option></select></label><label>Total<input name="total" type="number" step="0.01" value="0"></label><label style="grid-column:1/-1">Reclamação<textarea name="complaint"></textarea></label><label style="grid-column:1/-1">Diagnóstico<textarea name="diagnosis"></textarea></label>`,async d=>{d.customer_id=Number(d.customer_id);d.vehicle_id=Number(d.vehicle_id);await request('/work-orders',{method:'POST',headers:authHeaders(),body:JSON.stringify(d)});orders()})}}
function comingSoon(page,title){active(page,title);const messages={purchases:'Pedidos, cotações, fornecedores e entrada automática no estoque.',sales:'Orçamentos, venda balcão, descontos, comissões e fechamento.',finance:'Contas a pagar, contas a receber, fluxo de caixa e conciliação.',cash:'Abertura, movimentações e fechamento diário do caixa.',reports:'Indicadores e relatórios de vendas, estoque, clientes e serviços.',agenda:'Agendamentos de serviços, mecânicos e lembretes.',whatsapp:'Envio de orçamento, aprovação e aviso de veículo pronto.',settings:'Dados da empresa, parâmetros e personalização do sistema.',users:'Perfis de acesso, permissões e histórico de atividades.'};$('#page').innerHTML=`<div class="panel empty-module"><img src="assets/mascote-amigao.png" alt="Mascote"><h2>${esc(title)}</h2><p>${esc(messages[page]||'Este módulo está preparado para a próxima etapa do desenvolvimento.')}</p><span class="status">Estrutura visual preparada</span></div>`}
$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(q){loadPage('products');setTimeout(()=>{const s=$('#search');if(s){s.value=q;s.dispatchEvent(new Event('input'))}},250)}}};
if(token&&user)showApp();
